name: Build and Deploy Java Microservice

#on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Build Docker image
        run: cd {{github.workspace}/{{service_name}docker build -t ${{var.service_name}}:latest .

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Tagging the image
        run: docker tag ${{var.service_name}} ${{secrets.DOCKER_USERNAME}}/${{var.service_name}}

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{var.service_name}}
