name: Build and Deploy Java Microservice

on:
  push:
    branches:
      - master
      - develop
      - release 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: cd ${{github.workspace}}/account-service ; mvn clean install

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: cd ${{github.workspace}${{env.service_name} ;docker build -t ${{env.service_name}}:latest .

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Tagging the image
        run: docker tag ${{env.service_name}} ${{secrets.DOCKER_USERNAME}}/${{env.service_name}}

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{env.service_name}}
